#!/usr/bin/env bash
#Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.html
service nginx start
location="^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4;"
sudo sed -i "301 "$location" "/etc/nginx/sites-available/default"
service nginx restart
