#!/usr/bin/env bash
#Nginx server so that /redirect_me is redirecting to another page
apt-get -y update 
apt-get -y install nginx 
echo "Holberton School" | sudo tee /var/www/html/index.html 

default="/etc/nginx/sites-enabled/default"
location="location /redirect_me {rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;}"
sudo sed -i "30i $location" "$default"
service nginx start
