#!/usr/bin/env bash
#Nginx server so that /redirect_me is redirecting to another page
apt-get -y update 
apt-get -y install nginx 
echo "Holberton School" | sudo tee /var/www/html/index.html 

REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"  
sed -i "307 \ $REDIR" /etc/nginx/sites-available/default
service nginx start