#!/usr/bin/env bash
#Nginx server so that /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
sudo service nginx start

echo "Holberton School" > /var/www/html/index.html

otherdefault="/etc/nginx/sites-available/default"
location="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "30i $location" "$otherdefault"
echo "Ceci n'est pas une page" > /var/www/html/404.html
e404='/listen 80 default_server/a error_page 404 /404.html; location = /404.html {root /var/www/html;\n internal;}' 
sed -i "$e404" /etc/nginx/sites-available/default 
service nginx restart
