#!/usr/bin/env bash
# install and configure HAProxy

sudo apt show haproxy
sudo add-apt-repository ppa:vbernat/haproxy-1.7
sudo apt update
sudo apt install -y haproxy

echo -e "\nfrontend http
   bind *:80
   mode http
   default_backend web_backend" >> /etc/haproxy/haproxy.cfg

echo -e "\nbackend web_backend
   balance roundrobin
   server 1651-web-01 35.196.97.61:80 check
   server 1651-web-02 34.75.200.40:80 check" >> /etc/haproxy/haproxy.cfg
sudo service restart haproxy
