#!/usr/bin/env bash
# install and configure HAProxy
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.7
apt-get update
apt-get install haproxy=1.7.\*

echo -e "\nfrontend http
   bind *:80
   mode http
   default_backend web_backend\n" >> /etc/haproxy/haproxy.cfg

echo -e "\nbackend web_backend
   balance roundrobin
   option forwardfor
   server 1651-web-01 35.196.97.61:80 check
   server 1651-web-02 34.75.200.40:80 check" >> /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
