#!/usr/bin/env bash
#print repetion dependig conditionals
FILE="holbertonschool"
if [ -e "$FILE" ]
then
    echo "$FILE holbertonschool file exists"
    if [ -s "$FILE" ]
    then
        echo "$FILE holbertonschool file is empty"
    else
        echo "$FILE holbertonschool file is not empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "$FILE holbertonschool is a regular file"
    fi
else
    echo "$FILE holbertonschool file does not exist"
fi
